In [26]:
import torch
import numpy as np

In [27]:
x = torch.Tensor([1,2,3])
x

tensor([1., 2., 3.])

In [28]:
tensor = torch.ones(4,4)
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
tensor[:, 0]

tensor([1., 1., 1., 1.])

In [30]:
rand_tensor = torch.rand(3, 4)
rand_tensor.ndim

2

In [31]:
ones_tensor = torch.ones(3,4,dtype=int)
ones_tensor

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [32]:
tensor = torch.arange(5, 10,step=2, dtype=float)

In [33]:
tensor_like = torch.zeros_like(tensor)
tensor_like.device

device(type='cpu')

In [34]:
torch.max(tensor)

tensor(9., dtype=torch.float64)

In [35]:
tensor = torch.arange(1, 11)
tensor

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
tensor.reshape(5, -1)

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [37]:
tensor.view(5,-1)

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [38]:
a = torch.arange(1, 9)
b = torch.arange(2, 10)
torch.stack((a, b), dim=0)

tensor([[1, 2, 3, 4, 5, 6, 7, 8],
        [2, 3, 4, 5, 6, 7, 8, 9]])

In [39]:
a.unsqueeze(dim=1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]])

In [40]:
first = np.array([1,2,3])
second = torch.from_numpy(first)

In [41]:
first[0] = 100
second

tensor([100,   2,   3], dtype=torch.int32)

In [42]:
torch.rand(3,3)

tensor([[0.2266, 0.5936, 0.6638],
        [0.8242, 0.4715, 0.0772],
        [0.7189, 0.6633, 0.4234]])

In [43]:
torch.cuda.is_available()

False