In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random

In [12]:
arr = np.array([1,2,3,-4]).reshape(4, 1)
arr

array([[ 1],
       [ 2],
       [ 3],
       [-4]])

In [13]:
def softMax(z):
    e = np.exp(z)
    return e / np.sum(e, axis = 0)

In [14]:
softMax(arr)

array([[8.99759918e-02],
       [2.44580104e-01],
       [6.64837651e-01],
       [6.06253464e-04]])

In [15]:
def derivative_relu(x):
    return np.array(x > 0, dtype = np.float32)

In [16]:
derivative_relu(arr)

array([[1.],
       [1.],
       [1.],
       [0.]], dtype=float32)