In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

CLS

In [11]:
X = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [5, 4, 3, 6], [5, 6, 7, 8] , [3, 5, 6, 7] , [8, 5, 9, 5]])
X

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [5, 4, 3, 6],
       [5, 6, 7, 8],
       [3, 5, 6, 7],
       [8, 5, 9, 5]])

In [12]:
y=np.array([[1, 2, 3, 4, 5, 9], [3, 4, 5, 6, 7, 7], [5, 6, 7, 8, 9, 2], [2, 3, 4, 5, 6, 8], [9, 8, 7, 6, 5, 5], [1, 3, 5, 7, 8, 9]])
y

array([[1, 2, 3, 4, 5, 9],
       [3, 4, 5, 6, 7, 7],
       [5, 6, 7, 8, 9, 2],
       [2, 3, 4, 5, 6, 8],
       [9, 8, 7, 6, 5, 5],
       [1, 3, 5, 7, 8, 9]])

In [13]:
K = np.dot(np.dot(np.linalg.inv(np.dot(X.T, X)), X.T), y)

In [14]:
K

array([[-0.51042997,  0.06939123,  0.64921243,  1.22903363,  1.6905066 ,
         0.29757344],
       [ 2.26170711,  0.51905066, -1.22360579, -2.96626224, -4.47914006,
        -7.36462324],
       [-0.70604513, -0.43529161, -0.1645381 ,  0.10621541,  0.23286505,
         2.81736909],
       [-0.09120903,  0.66294168,  1.41709238,  2.17124308,  2.94657301,
         3.66347382]])

In [15]:
y_test = np.array([2,4,6,8,9,3])

In [16]:
x_test = np.dot(np.dot(y_test, K.T), np.linalg.inv(np.dot(K, K.T)))
x_test

array([10.88317176,  6.41113597,  9.08227691,  5.83842903])