In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

ILS

In [2]:
X=np.array([[1, 2, 3, 4], [4, 5, 6, 7], [5, 4, 3, 6], [5, 6, 7, 8], [3, 5,6 ,7], [8, 5, 9, 5]])
X

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [5, 4, 3, 6],
       [5, 6, 7, 8],
       [3, 5, 6, 7],
       [8, 5, 9, 5]])

In [3]:
y=np.array([4,6,7,8,3,7]).reshape((X.shape[0], 1))
y

array([[4],
       [6],
       [7],
       [8],
       [3],
       [7]])

In [4]:
P = np.dot(np.dot(np.linalg.inv(np.dot(y.T, y)), y.T),X)
P

array([[0.75336323, 0.73542601, 0.92376682, 0.98654709]])

In [5]:
y_test = 8
x_test = np.dot(y_test, P)
x_test

array([[6.02690583, 5.88340807, 7.39013453, 7.89237668]])