In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
X_train = pd.read_csv("./logistic_regression_datasets/train_X.csv")
print(X_train)
y_train = pd.read_csv("./logistic_regression_datasets/train_Y.csv")
X_test = pd.read_csv("./logistic_regression_datasets/test_X.csv")
y_test = pd.read_csv("./logistic_regression_datasets/test_Y.csv")

      Id  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0      0       3    0  22.0      1      0   7.2500         1
1      1       1    1  38.0      1      0  71.2833         0
2      2       3    1  26.0      0      0   7.9250         1
3      3       1    1  35.0      1      0  53.1000         1
4      4       3    0  35.0      0      0   8.0500         1
..   ...     ...  ...   ...    ...    ...      ...       ...
886  886       2    0  27.0      0      0  13.0000         1
887  887       1    1  19.0      0      0  30.0000         1
888  888       3    1  20.0      1      2  23.4500         1
889  889       1    0  26.0      0      0  30.0000         0
890  890       3    0  32.0      0      0   7.7500         2

[891 rows x 8 columns]


In [3]:
X_train = X_train.drop(["Id"], axis = 1)
y_train = y_train.drop(["Id"], axis = 1)
X_test = X_test.drop(["Id"], axis = 1)
y_test = y_test.drop(["Id"], axis = 1)

In [4]:
print(X_train.shape)
print(y_train.shape)

(891, 7)
(891, 1)


In [5]:
X_train = X_train.values.T
y_train = y_train.values.T
X_test = X_test.values.T
y_test = y_test.values.T


In [6]:
print(X_train.shape)
print(y_train.shape)

(7, 891)
(1, 891)


In [7]:
def sigmoid_predict(x):
    return 1 / (1 + np.exp(-x))

In [8]:
# def model(x, y, learning_rate, iter):
#     m = x.shape[1]
#     n = x.shape[0]

#     w = np.zeros((n,1))
#     B = 0

#     cost_his = []
#     for i in range (iter):
#         A = sigmoid_predict(np.dot(w.T, x) + B)

#         cost = (-1/m) * np.sum(y * np.log(A) + (1 - y) * np.log(1 - A))
#         cost_his.append(cost)

#         dw = 

In [9]:
arr1 = np.array([[1,2,3], [4, 5, 6], [7,8,9]])
arr2 = np.array([[1,2,3], [4, 5, 6], [7,8,9]])

print(arr1 * arr2)

print(np.dot(arr1, arr2))

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
