In [232]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd 


In [233]:
data = pd.read_excel("MTND2.xlsx")
data = data.drop("STT", axis = 1)
data = data.sample(frac=1)
data


GF   TBS  Natri Benzoate  Abs 260  Abs 265  Abs 270  Abs 275  Abs 280  \
0   3.0  3.0             3.0    0.333    0.452    0.584    0.625    0.534   
16  0.5  0.5             2.5    0.164    0.180    0.202    0.190    0.151   
23  0.5  1.0             1.0    0.123    0.145    0.171    0.175    0.152   
26  2.5  2.5             0.5    0.222    0.323    0.433    0.486    0.427   
32  2.5  3.0             2.5    0.340    0.446    0.565    0.603    0.519   
17  0.5  0.5             3.0    0.190    0.206    0.229    0.211    0.166   
21  0.5  2.5             0.5    0.129    0.174    0.227    0.262    0.247   
33  2.5  1.0             0.5    0.210    0.294    0.381    0.410    0.346   
31  2.5  3.0             2.0    0.308    0.416    0.536    0.580    0.503   
5   3.0  3.0             0.5    0.251    0.376    0.512    0.576    0.505   
30  2.5  3.0             1.5    0.290    0.400    0.522    0.571    0.498   
41  1.5  2.5             2.0    0.191    0.248    0.319    0.348    0.308   
2   7.0  7.0             2.0    0.575    0.848    1.143    1.283    1.128   
7   2.0  2.0             1.5    0.219    0.302    0.392    0.425    0.365   
29  2.5  3.0             0.5    0.250    0.359    0.480    0.540    0.480   
38  1.0  2.5             1.5    0.198    0.256    0.322    0.351    0.313   
12  0.5  0.5             0.5    0.081    0.101    0.122    0.129    0.113   
24  2.5  2.5             1.5    0.265    0.364    0.475    0.520    0.452   
8   2.0  2.0             1.0    0.204    0.286    0.375    0.412    0.358   
10  1.0  1.0             1.0    0.130    0.170    0.214    0.227    0.194   
27  2.5  2.5             2.0    0.283    0.382    0.493    0.530    0.454   
25  2.5  2.5             1.0    0.251    0.353    0.465    0.513    0.448   
22  0.5  3.0             0.5    0.153    0.203    0.263    0.304    0.288   
19  0.5  1.5             0.5    0.103    0.135    0.172    0.192    0.176   
43  1.2  1.5             1.0    0.163    0.238    0.323    0.372    0.337   
6   2.0  2.0             2.0    0.238    0.319    0.409    0.435    0.370   
34  2.5  1.0             1.0    0.231    0.313    0.397    0.418    0.349   
15  0.5  0.5             2.0    0.119    0.139    0.161    0.161    0.136   
11  1.0  1.0             0.5    0.115    0.156    0.201    0.218    0.190   
39  1.0  2.5             1.0    0.175    0.234    0.301    0.336    0.304   
1   3.0  3.0             2.0    0.301    0.423    0.556    0.608    0.526   
28  2.5  2.5             2.5    0.307    0.406    0.520    0.552    0.471   
20  0.5  2.0             0.5    0.117    0.156    0.201    0.229    0.214   
3   3.0  3.0             1.5    0.283    0.405    0.537    0.592    0.513   
4   3.0  3.0             1.0    0.263    0.386    0.519    0.577    0.503   
36  2.5  1.0             2.0    0.278    0.361    0.450    0.460    0.377   
14  0.5  0.5             1.5    0.124    0.142    0.164    0.161    0.134   
35  2.5  1.0             1.5    0.249    0.331    0.418    0.435    0.358   
18  0.5  1.0             0.5    0.097    0.124    0.154    0.167    0.151   
13  0.5  0.5             1.0    0.107    0.126    0.148    0.149    0.126   
42  1.5  2.5             2.5    0.235    0.290    0.360    0.380    0.329   
40  1.0  2.5             0.5    0.154    0.214    0.281    0.321    0.294   
9   2.0  2.0             0.5    0.188    0.272    0.361    0.401    0.350   
37  2.5  1.0             2.5    0.293    0.374    0.462    0.468    0.380   

    Abs 285  Abs 290  
0     0.240    0.052  
16    0.071    0.035  
23    0.089    0.047  
26    0.210    0.052  
32    0.251    0.073  
17    0.076    0.037  
21    0.161    0.059  
33    0.145    0.044  
31    0.243    0.064  
5     0.238    0.054  
30    0.244    0.064  
41    0.163    0.033  
2     0.534    0.113  
7     0.168    0.041  
29    0.246    0.069  
38    0.177    0.055  
12    0.063    0.032  
24    0.219    0.055  
8     0.171    0.046  
10    0.094    0.032  
27    0.210    0.048  
25    0.218    0.055  
22    0.1

In [234]:
# Split data into train and test data
data_train = data[:int(0.7 * len(data))].values
data_test = data[int(0.7 * len(data)):].values
# Convert data table to X and Y matricses
X_train = data_train[:,0:3].astype(float) 
Y_train = data_train[:,3:].reshape(-1, 7).astype(float)
X_test = data_test[:,0:3].astype(float) 
Y_test = data_test[:,3:].reshape(-1, 7).astype(float)
print(Y_train.shape)
# np.linalg.det(np.dot(X_train.T, X_train))

(30, 7)


In [235]:
Y_chunks = np.array_split(Y_train, len(Y_train) / 8)

In [236]:
X_chunks = np.array_split(X_train, len(Y_train) / 8)

In [237]:
hidden_nodes = int((Y_train.shape[0] / (2 * (Y_train.shape[1] + X_train.shape[1]))))
print(hidden_nodes)

1


### ACTIVATION FUNCTIONS


In [238]:
def ReLU(input):
    return np.maximum(input, 0)
def leaky_ReLU(input):
    return np.maximum(0.01 * input, input)
def Linear(input):
    return input
def Sigmoid(input):
    return 1 / (1 + np.exp(-input))
def Swish(input):
    return input * Sigmoid(input)


In [239]:
def ReLU_de(input):
    return (input > 0) * 1
def leaky_ReLU_de(input):
    if input >= 0:
        return 1
    else:
        return 0.01
def Linear_de(input):
    return 1
def Sigmoid_de(input):
    return np.exp(input)/ np.square(np.exp(input) + 1)
def Swish_de(input):
    return Swish(input) + Sigmoid(input)*(1 - Swish(input))

In [240]:
def deriative_func(func_list):
    deriative_funcs = []
    for func in func_list:
        if func.__name__ == "ReLU":
            deriative_funcs.append(ReLU_de)
        if func.__name__ == "leaky_ReLU":
            deriative_funcs.append(leaky_ReLU_de)
        if func.__name__ == "Linear":
            deriative_funcs.append(Linear_de)
        if func.__name__ == "Sigmoid":
            deriative_funcs.append(Sigmoid_de)
        if func.__name__ == "Swish":
            deriative_funcs.append(Swish_de)
    return deriative_funcs

In [241]:
class Neural_Network:
    def __init__(self, n_inputs, n_outputs, n_hiddenlayers, n_hiddenlayernodes_list, layerfunc_list):
        self.n_hiddenlayers = n_hiddenlayers
        # Init weights list
        self.weights = []
        self.weights.append(np.random.rand(n_inputs, n_hiddenlayernodes_list[0]))
        for i in range(1, n_hiddenlayers):
            self.weights.append(np.random.rand(n_hiddenlayernodes_list[i - 1], n_hiddenlayernodes_list[i]))
        self.weights.append(np.random.rand(n_hiddenlayernodes_list[n_hiddenlayers - 1], n_outputs))
        
        # Init bias list
        self.bias = []
        for i in n_hiddenlayernodes_list:
            self.bias.append(np.zeros((1, i)))
        self.bias.append(np.zeros((1, n_outputs)))
        # for i in range (len(self.bias)):
        #     print(self.bias[i].shape)

        # Init deriative functions list
        self.deriative_funcs = deriative_func(layerfunc_list)
        # print(len(self.weights))
    def fit(self, input_data, target_data, iter):
        for i in range (iter):
            # FORWARD PASS
            layer_inputs = []
            layer_outputs = [input_data]
            for i in range (0, self.n_hiddenlayers + 1):
                layer_inputs.append(np.dot(layer_outputs[i], self.weights[i]) + self.bias[i])
                layer_outputs.append(self.deriative_funcs[i](layer_inputs[i]))
            # BACKPROPAGATION
            l3_delta = l3_output - target_data
            d_weight3 = np.dot(l2_output.T, l3_delta)
            d_bias3 = np.dot(np.ones((1, l3_delta.shape[0])), l3_delta)

            l2_delta = np.dot(l3_delta, self.weight3.T) * ReLU_de(l2_input)
            d_weight2 = np.dot(l1_output.T, l2_delta)
            d_bias2 = np.dot(np.ones((1, l2_delta.shape[0])), l2_delta)

            l1_delta = np.dot(l2_delta, self.weight2.T) * ReLU_de(l1_input)
            d_weight1 = np.dot(input_data.T, l1_delta)
            d_bias1 = np.dot(np.ones((1, l1_delta.shape[0])), l1_delta)

            self.weight3 -= 0.001 * d_weight3
            self.bias3 -= 0.001 * d_bias3
            self.weight2 -= 0.001 * d_weight2
            self.bias2 -= 0.001 * d_bias2
            self.weight1 -= 0.001 * d_weight1
            self.bias1 -= 0.001 * d_bias1


    def predict(self, input_data):
        l1_input = np.dot(input_data, self.weight1) + self.bias1
        l1_output = ReLU(l1_input)

        l2_input = np.dot(l1_output, self.weight2) + self.bias2
        l2_output = ReLU(l2_input)

        l3_input = np.dot(l2_output, self.weight3) + self.bias3
        l3_output = l3_input
        return l3_output
        

In [242]:
model = Neural_Network(Y_train.shape[1], X_train.shape[1],3, [3,4,5], [Sigmoid, ReLU, ReLU, Linear])
# print(len(Y_chunks))
for i in range(len(Y_chunks)):
    model.fit(Y_chunks[i], X_chunks[i], 1000)
# print(ReLU(Y_train))
# print(model.predict(Y_test))
X_pred = model.predict(Y_test)
print(X_pred)
print(X_test)

(1, 3)
(1, 4)
(1, 5)
(1, 3)
[array([[1.67066602, 0.67888505, 0.64520535],
       [0.61112623, 0.23268858, 0.22418398],
       [0.55829589, 0.2231928 , 0.21567422],
       [1.27616547, 0.53105219, 0.50535151],
       [1.67458113, 0.67890037, 0.64924465],
       [0.68618075, 0.25908082, 0.25003215],
       [0.76871761, 0.32389776, 0.31909968],
       [1.08478384, 0.4417821 , 0.41146845],
       [1.57984305, 0.64529182, 0.61669156],
       [1.48061673, 0.61831128, 0.58434677]]), array([[0.32052132, 0.18726138, 0.40655007, 0.23444774],
       [0.416937  , 0.28074568, 0.49064506, 0.28297685],
       [0.41990308, 0.28397994, 0.49287364, 0.28424907],
       [0.35914609, 0.22428113, 0.44067296, 0.25415144],
       [0.32012637, 0.18692586, 0.40610821, 0.23426261],
       [0.41200486, 0.27566392, 0.48663577, 0.28068492],
       [0.40477726, 0.26921184, 0.47972415, 0.27674909],
       [0.37833651, 0.24240461, 0.45797441, 0.26403998],
       [0.32927386, 0.19561389, 0.41428013, 0.23896825],
      

AttributeError: 'Neural_Network' object has no attribute 'weight1'

In [ ]:
print(((X_pred - X_test) / X_test ) * 100)

[[-35.42103363 107.01465378 162.76902756]
 [ 69.03921515 -50.82291848 178.03013407]
 [-11.36806531   7.05432278 -19.31722388]
 [-23.84852749 -27.81432296  43.62188531]
 [-10.75546377   9.76207671  25.2680018 ]
 [-14.73167458   3.3783414   22.0250844 ]
 [ 12.75348593  12.87854881 -52.22467765]
 [-23.84852749  44.37135409  -4.25207646]
 [-15.43185951   2.61313161 144.46688145]
 [-11.53036895 -29.75904854 -32.88221986]
 [ -8.64064896  12.07329041 -16.83761678]
 [122.13692934 -49.34763214 172.76331386]
 [-28.56436469 125.74824118 -13.54385827]
 [-17.95442749   1.8945587  154.10636894]]
