In [800]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd 


In [801]:
data = pd.read_excel("MTND2.xlsx")
data = data.drop("STT", axis = 1)
data = data.sample(frac=1)
data


GF   TBS  Natri Benzoate  Abs 260  Abs 265  Abs 270  Abs 275  Abs 280  \
2   7.0  7.0             2.0    0.575    0.848    1.143    1.283    1.128   
40  1.0  2.5             0.5    0.154    0.214    0.281    0.321    0.294   
36  2.5  1.0             2.0    0.278    0.361    0.450    0.460    0.377   
42  1.5  2.5             2.5    0.235    0.290    0.360    0.380    0.329   
18  0.5  1.0             0.5    0.097    0.124    0.154    0.167    0.151   
10  1.0  1.0             1.0    0.130    0.170    0.214    0.227    0.194   
6   2.0  2.0             2.0    0.238    0.319    0.409    0.435    0.370   
28  2.5  2.5             2.5    0.307    0.406    0.520    0.552    0.471   
13  0.5  0.5             1.0    0.107    0.126    0.148    0.149    0.126   
9   2.0  2.0             0.5    0.188    0.272    0.361    0.401    0.350   
34  2.5  1.0             1.0    0.231    0.313    0.397    0.418    0.349   
37  2.5  1.0             2.5    0.293    0.374    0.462    0.468    0.380   
7   2.0  2.0             1.5    0.219    0.302    0.392    0.425    0.365   
19  0.5  1.5             0.5    0.103    0.135    0.172    0.192    0.176   
0   3.0  3.0             3.0    0.333    0.452    0.584    0.625    0.534   
20  0.5  2.0             0.5    0.117    0.156    0.201    0.229    0.214   
1   3.0  3.0             2.0    0.301    0.423    0.556    0.608    0.526   
31  2.5  3.0             2.0    0.308    0.416    0.536    0.580    0.503   
17  0.5  0.5             3.0    0.190    0.206    0.229    0.211    0.166   
11  1.0  1.0             0.5    0.115    0.156    0.201    0.218    0.190   
12  0.5  0.5             0.5    0.081    0.101    0.122    0.129    0.113   
27  2.5  2.5             2.0    0.283    0.382    0.493    0.530    0.454   
16  0.5  0.5             2.5    0.164    0.180    0.202    0.190    0.151   
43  1.2  1.5             1.0    0.163    0.238    0.323    0.372    0.337   
15  0.5  0.5             2.0    0.119    0.139    0.161    0.161    0.136   
29  2.5  3.0             0.5    0.250    0.359    0.480    0.540    0.480   
38  1.0  2.5             1.5    0.198    0.256    0.322    0.351    0.313   
39  1.0  2.5             1.0    0.175    0.234    0.301    0.336    0.304   
8   2.0  2.0             1.0    0.204    0.286    0.375    0.412    0.358   
30  2.5  3.0             1.5    0.290    0.400    0.522    0.571    0.498   
33  2.5  1.0             0.5    0.210    0.294    0.381    0.410    0.346   
21  0.5  2.5             0.5    0.129    0.174    0.227    0.262    0.247   
3   3.0  3.0             1.5    0.283    0.405    0.537    0.592    0.513   
23  0.5  1.0             1.0    0.123    0.145    0.171    0.175    0.152   
25  2.5  2.5             1.0    0.251    0.353    0.465    0.513    0.448   
4   3.0  3.0             1.0    0.263    0.386    0.519    0.577    0.503   
32  2.5  3.0             2.5    0.340    0.446    0.565    0.603    0.519   
14  0.5  0.5             1.5    0.124    0.142    0.164    0.161    0.134   
5   3.0  3.0             0.5    0.251    0.376    0.512    0.576    0.505   
41  1.5  2.5             2.0    0.191    0.248    0.319    0.348    0.308   
24  2.5  2.5             1.5    0.265    0.364    0.475    0.520    0.452   
22  0.5  3.0             0.5    0.153    0.203    0.263    0.304    0.288   
35  2.5  1.0             1.5    0.249    0.331    0.418    0.435    0.358   
26  2.5  2.5             0.5    0.222    0.323    0.433    0.486    0.427   

    Abs 285  Abs 290  
2     0.534    0.113  
40    0.172    0.055  
36    0.149    0.043  
42    0.169    0.037  
18    0.090    0.040  
10    0.094    0.032  
6     0.166    0.039  
28    0.216    0.051  
13    0.067    0.033  
9     0.168    0.046  
34    0.146    0.046  
37    0.147    0.041  
7     0.168    0.041  
19    0.108    0.044  
0     0.240    0.052  
20    0.138    0.052  
1     0.241    0.052  
31    0.243    0.064  
17    0.076    0.037  
11    0.095    0.033  
12    0.063    0.032  
27    0.210    0.048  
16    0.0

In [802]:
# Split data into train and test data
data_train = data[:int(0.7 * len(data))].values
data_test = data[int(0.7 * len(data)):].values
# Convert data table to X and Y matricses
X_train = data_train[:,0:3].astype(float) 
Y_train = data_train[:,3:].reshape(-1, 7).astype(float)
X_test = data_test[:,0:3].astype(float) 
Y_test = data_test[:,3:].reshape(-1, 7).astype(float)
print(Y_train.shape)
# np.linalg.det(np.dot(X_train.T, X_train))

(30, 7)


In [803]:
Y_chunks = np.array_split(Y_train, len(Y_train) / 8)

In [804]:
X_chunks = np.array_split(X_train, len(Y_train) / 8)

In [805]:
hidden_nodes = int((Y_train.shape[0] / (2 * (Y_train.shape[1] + X_train.shape[1]))))
print(hidden_nodes)

1


### ACTIVATION FUNCTIONS


In [6]:
def ReLU(input):
    return np.maximum(input, 0)
def leaky_ReLU(input):
    return np.maximum(0.01 * input, input)
def Linear(input):
    return input
def Sigmoid(input):
    return 1 / (1 + np.exp(-input))
def Swish(input):
    return input * Sigmoid(input)


In [9]:
def ReLU_de(input):
    return (input > 0) * 1
def leaky_ReLU_de(input):
    if input >= 0:
        return 1
    else:
        return 0.01
def Linear_de(input):
    return 1
def Sigmoid_de(input):
    return np.exp(input)/ np.square(np.exp(input) + 1)
def Swish_de(input):
    return Swish(input) + Sigmoid(input)*(1 - Swish(input))

In [807]:
def derivative_func(func):
    if func.__name__ == "ReLU":
        return ReLU_de

In [808]:
class Neural_Network:
    def __init__(self, n_inputs, n_outputs, n_hiddenlayers):
        self.weight1 = 0.1 * np.random.randn(n_inputs, n1_hiddennodes)
        self.weight2 = 0.1 * np.random.randn(n1_hiddennodes, n2_hiddennodes)
        self.weight3 = 0.1 * np.random.randn(n2_hiddennodes, n_outputs)
        self.bias1 = np.zeros((1, n1_hiddennodes))
        self.bias2 = np.zeros((1, n2_hiddennodes))
        self.bias3 = np.zeros((1, n_outputs))
    def fit(self, input_data, target_data, iter):
        for i in range (iter):
            # FORWARD PASS
            l1_input = np.dot(input_data, self.weight1) + self.bias1
            l1_output = ReLU(l1_input)

            l2_input = np.dot(l1_output, self.weight2) + self.bias2
            l2_output = ReLU(l2_input)

            l3_input = np.dot(l2_output, self.weight3) + self.bias3
            l3_output = l3_input
            
            # BACKPROPAGATION
            l3_delta = l3_output - target_data
            d_weight3 = np.dot(l2_output.T, l3_delta)
            d_bias3 = np.dot(np.ones((1, l3_delta.shape[0])), l3_delta)

            l2_delta = np.dot(l3_delta, self.weight3.T) * ReLU_de(l2_input)
            d_weight2 = np.dot(l1_output.T, l2_delta)
            d_bias2 = np.dot(np.ones((1, l2_delta.shape[0])), l2_delta)

            l1_delta = np.dot(l2_delta, self.weight2.T) * ReLU_de(l1_input)
            d_weight1 = np.dot(input_data.T, l1_delta)
            d_bias1 = np.dot(np.ones((1, l1_delta.shape[0])), l1_delta)

            self.weight3 -= 0.001 * d_weight3
            self.bias3 -= 0.001 * d_bias3
            self.weight2 -= 0.001 * d_weight2
            self.bias2 -= 0.001 * d_bias2
            self.weight1 -= 0.001 * d_weight1
            self.bias1 -= 0.001 * d_bias1


    def predict(self, input_data):
        l1_input = np.dot(input_data, self.weight1) + self.bias1
        l1_output = ReLU(l1_input)

        l2_input = np.dot(l1_output, self.weight2) + self.bias2
        l2_output = ReLU(l2_input)

        l3_input = np.dot(l2_output, self.weight3) + self.bias3
        l3_output = l3_input
        return l3_output
        

In [809]:
model = Neural_Network(Y_train.shape[1], 2, 2, X_train.shape[1])
# print(len(Y_chunks))
for i in range(len(Y_chunks)):
    model.fit(Y_chunks[i], X_chunks[i], 1000)
# print(ReLU(Y_train))
# print(model.predict(Y_test))
X_pred = model.predict(Y_test)
print(X_pred)
print(X_test)

[[1.61447416 2.07014654 1.31384514]
 [0.84519608 1.22942704 1.39015067]
 [2.65895804 3.21162968 1.21024164]
 [0.38075736 0.72185677 1.43621885]
 [2.23111341 2.74405192 1.25268002]
 [2.55804976 3.10135024 1.22025084]
 [2.81883715 3.38635646 1.19438306]
 [0.38075736 0.72185677 1.43621885]
 [2.53704421 3.07839395 1.22233441]
 [1.32704447 1.75602379 1.3423556 ]
 [2.28398378 2.80183226 1.24743575]
 [1.11068465 1.51957104 1.36381657]
 [1.78589088 2.25748241 1.29684213]
 [2.05113931 2.54736397 1.27053184]]
[[2.5 1.  0.5]
 [0.5 2.5 0.5]
 [3.  3.  1.5]
 [0.5 1.  1. ]
 [2.5 2.5 1. ]
 [3.  3.  1. ]
 [2.5 3.  2.5]
 [0.5 0.5 1.5]
 [3.  3.  0.5]
 [1.5 2.5 2. ]
 [2.5 2.5 1.5]
 [0.5 3.  0.5]
 [2.5 1.  1.5]
 [2.5 2.5 0.5]]


In [810]:
print(((X_pred - X_test) / X_test ) * 100)

[[-35.42103363 107.01465378 162.76902756]
 [ 69.03921515 -50.82291848 178.03013407]
 [-11.36806531   7.05432278 -19.31722388]
 [-23.84852749 -27.81432296  43.62188531]
 [-10.75546377   9.76207671  25.2680018 ]
 [-14.73167458   3.3783414   22.0250844 ]
 [ 12.75348593  12.87854881 -52.22467765]
 [-23.84852749  44.37135409  -4.25207646]
 [-15.43185951   2.61313161 144.46688145]
 [-11.53036895 -29.75904854 -32.88221986]
 [ -8.64064896  12.07329041 -16.83761678]
 [122.13692934 -49.34763214 172.76331386]
 [-28.56436469 125.74824118 -13.54385827]
 [-17.95442749   1.8945587  154.10636894]]
