In [32]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# from sklearn.cross_decomposition import 
# from sklearn.model_selection import cross_val_predict
# from sklearn.metrics import mean_squared_error, r2_score

In [33]:
df = pd.read_excel("MTND3.xlsx")
df = df.drop("STT", axis = 1)
df



GF   TBS  Natri Benzoate  Abs 260  Abs 262  Abs 264  Abs 266  Abs 268  \
0   3.0  3.0             3.0    0.333    0.377    0.426    0.478    0.533   
1   3.0  3.0             2.0    0.301    0.346    0.397    0.450    0.505   
2   7.0  7.0             0.0    0.498    0.600    0.720    0.844    0.965   
3   7.0  7.0             2.0    0.575    0.675    0.788    0.906    1.028   
4   3.0  3.0             1.5    0.283    0.328    0.379    0.431    0.486   
5   3.0  3.0             1.0    0.263    0.309    0.359    0.412    0.467   
6   3.0  3.0             0.5    0.251    0.298    0.349    0.404    0.459   
7   2.0  2.0             2.0    0.238    0.268    0.301    0.336    0.374   
8   2.0  2.0             1.5    0.219    0.250    0.284    0.320    0.357   
9   2.0  2.0             1.0    0.204    0.234    0.269    0.304    0.340   
10  2.0  2.0             0.5    0.188    0.219    0.254    0.290    0.326   
11  1.0  1.0             1.0    0.130    0.145    0.162    0.179    0.197   
12  1.0  1.0             0.5    0.115    0.130    0.148    0.165    0.184   
13  0.5  0.5             0.5    0.081    0.088    0.096    0.105    0.114   
14  0.5  0.5             1.0    0.107    0.114    0.122    0.130    0.140   
15  0.5  0.5             1.5    0.124    0.131    0.139    0.146    0.156   
16  0.5  0.5             2.0    0.119    0.126    0.134    0.143    0.153   
17  0.5  0.5             2.5    0.164    0.171    0.177    0.184    0.194   
18  0.5  0.5             3.0    0.190    0.197    0.203    0.210    0.220   
19  0.5  1.0             0.5    0.097    0.107    0.118    0.129    0.142   
20  0.5  1.5             0.5    0.103    0.114    0.128    0.142    0.157   
21  0.5  2.0             0.5    0.117    0.131    0.147    0.165    0.183   
22  0.5  2.5             0.5    0.129    0.145    0.164    0.184    0.206   
23  0.5  3.0             0.5    0.153    0.171    0.192    0.214    0.239   
24  0.5  1.0             1.0    0.123    0.131    0.140    0.150    0.161   
25  2.5  2.5             1.5    0.265    0.301    0.342    0.386    0.431   
26  2.5  2.5             1.0    0.251    0.288    0.331    0.375    0.421   
27  2.5  2.5             0.5    0.222    0.259    0.302    0.345    0.390   
28  2.5  2.5             2.0    0.283    0.320    0.360    0.403    0.450   
29  2.5  2.5             2.5    0.307    0.343    0.385    0.428    0.476   
30  2.5  3.0             0.5    0.250    0.289    0.335    0.383    0.433   
31  2.5  3.0             1.5    0.290    0.330    0.376    0.424    0.474   
32  2.5  3.0             2.0    0.308    0.347    0.392    0.439    0.489   
33  2.5  3.0             2.5    0.340    0.379    0.424    0.469    0.519   
34  2.5  1.0             0.5    0.210    0.241    0.277    0.312    0.348   
35  2.5  1.0             1.0    0.231    0.261    0.295    0.329    0.365   
36  2.5  1.0             1.5    0.249    0.279    0.314    0.348    0.385   
37  2.5  1.0             2.0    0.278    0.309    0.343    0.378    0.416   
38  2.5  1.0             2.5    0.293    0.323    0.357    0.392    0.429   
39  1.0  2.5             1.5    0.198    0.219    0.243    0.268    0.296   
40  1.0  2.5             1.0    0.175    0.196    0.221    0.247    0.275   
41  1.0  2.5             0.5    0.154    0.176    0.201    0.227    0.254   
42  1.5  2.5             2.0    0.191    0.212    0.236    0.261    0.290   
43  1.5  2.5             2.5    0.235    0.256    0.279    0.303    0.332   
44  1.2  1.5             1.0    0.163    0.190    0.222    0.255    0.289   

    Abs 270  Abs 272  Abs 274  Abs 276  Abs 278  Abs 280  Abs 282  Abs 284  \
0     0.584    0.618    0.629    0.615    0.583    0.534    0.436    0.302   
1     0.556    0.594    0.611    0.599    0.569    0.526    0.431    0.301   
2     1.082    1.184    1.242    1.231    1.175    1.108    0.939    0.669   
3     1.143    1.232    1.281    1.265    1.205    1.128    0.942    0.666   
4     0.537    0.576    0.593    0.582    0.554    0.513    0.423    0.

In [34]:
df_train = df[:int(0.8 * len(df))].values
df_test = df[int(0.8 * len(df)):].values
# df_train
X_train = df_train[:,0:3].astype(float)
Y_train = df_train[:,3:].reshape(-1,16).astype(float)
X_test = df_test[:,0:3].astype(float)
Y_test = df_test[:,3:].reshape(-1,16).astype(float)

print(Y_train.shape)
# np.linalg.det(np.dot(X_train.T, X_train))

(36, 16)


In [35]:
K = np.dot(np.dot(np.linalg.inv(np.dot(X_train.T, X_train)), X_train.T), Y_train)
K

array([[ 0.04307437,  0.05353657,  0.06532857,  0.07714013,  0.08852352,
         0.09900683,  0.10683896,  0.10925871,  0.10404721,  0.09598508,
         0.08644935,  0.06297343,  0.0326913 ,  0.01192814,  0.00052045,
        -0.00483023],
       [ 0.03001484,  0.03426939,  0.03949572,  0.04528971,  0.051494  ,
         0.05789493,  0.06433006,  0.07008612,  0.07341438,  0.07332737,
         0.07311025,  0.0716374 ,  0.06304074,  0.04769882,  0.03207671,
         0.02066684],
       [ 0.05077652,  0.05076912,  0.05020894,  0.0497535 ,  0.05073155,
         0.05098974,  0.04777339,  0.04320064,  0.04013851,  0.03717098,
         0.02952584,  0.02012467,  0.01382999,  0.01065382,  0.00925876,
         0.0089032 ]])

In [36]:
P = np.dot(np.dot(np.linalg.inv(np.dot(Y_train.T, Y_train)), Y_train.T),X_train)
P

array([[   7.74263418, -104.36922198, -119.69125733],
       [ -15.55358116,   66.88866313,  100.23133187],
       [  42.94378557,  -21.20765164, -138.29234945],
       [  -6.33497324,   39.10309531,  232.49342939],
       [ -51.38218446,  103.31753608,  203.36718517],
       [  -9.03732983,   28.51975998, -116.31633545],
       [  41.95809963,  -89.20653412,  -16.20348931],
       [ -37.05087753,  -16.0553631 ,  -41.83032741],
       [  41.10431514,  -61.13548971, -101.27277162],
       [ -54.83726684,   41.78055868,  -53.8628968 ],
       [  51.78727239,  -11.88449547,   32.32266369],
       [  46.67700485,    1.51582812,   25.07946564],
       [ -58.36854629,   50.32411995,   41.36917588],
       [ -32.11771035,    2.48619806,   -3.22667592],
       [  35.87363985,   17.82932865,   93.76248739],
       [  -4.72439876,  -43.00708019, -140.76105288]])

In [37]:
X_cal = np.dot(Y_test, P)
print(Y_test)
print(X_cal)

[[0.249 0.279 0.314 0.348 0.385 0.418 0.438 0.441 0.424 0.397 0.358 0.281
  0.185 0.111 0.065 0.041]
 [0.278 0.309 0.343 0.378 0.416 0.45  0.468 0.467 0.449 0.42  0.377 0.293
  0.191 0.115 0.068 0.043]
 [0.293 0.323 0.357 0.392 0.429 0.462 0.478 0.475 0.455 0.427 0.38  0.293
  0.19  0.113 0.066 0.041]
 [0.198 0.219 0.243 0.268 0.296 0.322 0.341 0.349 0.348 0.335 0.313 0.271
  0.21  0.145 0.09  0.055]
 [0.175 0.196 0.221 0.247 0.275 0.301 0.322 0.334 0.334 0.322 0.304 0.266
  0.207 0.142 0.089 0.054]
 [0.154 0.176 0.201 0.227 0.254 0.281 0.304 0.318 0.319 0.309 0.294 0.261
  0.204 0.142 0.089 0.055]
 [0.191 0.212 0.236 0.261 0.29  0.319 0.338 0.347 0.346 0.333 0.308 0.263
  0.198 0.13  0.073 0.033]
 [0.235 0.256 0.279 0.303 0.332 0.36  0.376 0.38  0.376 0.361 0.329 0.276
  0.205 0.136 0.077 0.037]
 [0.163 0.19  0.222 0.255 0.289 0.323 0.351 0.369 0.37  0.356 0.337 0.295
  0.225 0.148 0.086 0.044]]
[[2.4354664  0.98658802 1.69128285]
 [2.59201682 1.05076538 2.5795599 ]
 [2.42811951 1.222

In [38]:
ss = ((X_cal - X_test) / X_test ) * 100
ss

array([[ -2.58134404,  -1.34119819,  12.75219014],
       [  3.68067271,   5.07653781,  28.97799479],
       [ -2.87521953,  22.21178597,  37.15668245],
       [ -3.07919493,   5.29512634,  41.10682764],
       [  4.27631669,   3.43533733,  46.58099602],
       [  7.1847177 ,  -0.17334472,  22.61173634],
       [-25.1571897 ,  -1.93518887,  -7.13977247],
       [-25.46989388,  -0.23018393,  25.44536435],
       [ 17.62114626,  88.15456331, -45.50069818]])